# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0017_auto_20170625_1622'),
        ('oauth', '0002_auto_20170612_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cover', versatileimagefield.fields.VersatileImageField(help_text='Upload high quality image to use as cover photo.', upload_to='news_%Y')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauth.UserProfile')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
