# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date'], 'verbose_name_plural': 'news'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='created_at',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default='2017-06-27'),
            preserve_default=False,
        ),
    ]
