# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170625_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Club'),
        ),
    ]
