# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170625_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
