# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_update_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
