# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20170610_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='topic',
        ),
        migrations.AddField(
            model_name='answer',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.Topic'),
            preserve_default=False,
        ),
    ]
