# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20170612_1258'),
        ('forum', '0014_auto_20170612_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favourite', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.UserProfile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Topic')),
            ],
        ),
    ]
