# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20170629_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at']},
        ),
    ]
