# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_auto_20170716_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
