# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_auto_20170717_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
