# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 20:00
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_auto_20170717_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
