# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0002_auto_20170612_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cover', versatileimagefield.fields.VersatileImageField(upload_to='club_%Y')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='oauth.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('GP', 'Google Plus'), ('IG', 'Instagram'), ('GH', 'GitHub'), ('FK', 'Flickr'), ('YT', 'YouTube')], max_length=2)),
                ('icon_class', models.CharField(blank=True, max_length=32, null=True)),
                ('fa_icon', models.CharField(blank=True, max_length=32, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cover', versatileimagefield.fields.VersatileImageField(upload_to='society_%Y')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='oauth.UserProfile')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secy', to='oauth.UserProfile')),
                ('vice_secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vice_secy', to='oauth.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Society'),
        ),
        migrations.AddField(
            model_name='club',
            name='vice_captain_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vice_cap_one', to='oauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='club',
            name='vice_captain_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vice_cap_two', to='oauth.UserProfile'),
        ),
    ]
