# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170622_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='year',
        ),
        migrations.AddField(
            model_name='society',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='society',
            name='year',
            field=models.CharField(choices=[('2008', 2008), ('2009', 2009), ('2010', 2010), ('2011', 2011), ('2012', 2012), ('2013', 2013), ('2014', 2014), ('2015', 2015), ('2016', 2016), ('2017', 2017), ('2018', 2018)], max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Not a valid year!')]),
        ),
    ]
