# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 11:59
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170622_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Cover PPOI'),
        ),
        migrations.AlterField(
            model_name='society',
            name='cover',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='society_%Y', verbose_name='Cover'),
        ),
    ]
