# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_society_ppoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
