# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_club_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='fa_icon',
            field=models.CharField(choices=[('fa fa-facebook', 'Facebook'), ('fa fa-twitter', 'Twitter'), ('fa fa-google-plus', 'Google Plus'), ('fa fa-instagram', 'Instagram'), ('fa fa-github', 'GitHub'), ('fa fa-youtube', 'YouTube'), ('fa fa-envelope-o', 'Email')], default='fb-ic', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(choices=[('fb-ic', 'Facebook'), ('tw-ic', 'Twitter'), ('gplus-ic', 'Google Plus'), ('ins-ic', 'Instagram'), ('git-ic', 'GitHub'), ('yt-ic', 'YouTube'), ('email-ic', 'Email')], default='fb-ic', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='social_media',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('GP', 'Google Plus'), ('IG', 'Instagram'), ('GH', 'GitHub'), ('YT', 'YouTube'), ('EM', 'Email')], max_length=2),
        ),
    ]
