# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170622_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='cover',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Upload high quality picture', null=True, upload_to='club_%Y'),
        ),
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(help_text='This will be used as URL. /club/slug', unique=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='cover',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Upload high quality picture', null=True, upload_to='society_%Y', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='society',
            name='slug',
            field=models.SlugField(help_text='This will be used as URL. /society/slug', unique=True),
        ),
    ]
