# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170623_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cover Height'),
        ),
        migrations.AddField(
            model_name='society',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cover Width'),
        ),
        migrations.AlterField(
            model_name='society',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Cover'),
        ),
    ]
