# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170623_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='height',
        ),
        migrations.RemoveField(
            model_name='society',
            name='ppoi',
        ),
        migrations.RemoveField(
            model_name='society',
            name='width',
        ),
    ]
