# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170623_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='custom_html',
            field=models.TextField(blank=True, help_text='Add custom HTML to view on club page.', null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='skin',
            field=models.CharField(blank=True, choices=[('white-skin', 'White'), ('black-skin', 'Black'), ('cyan-skin', 'Cyan'), ('mdb-skin', 'MDB'), ('deep-purple-skin', 'Deep Purple'), ('navy-blue-skin', 'Navy Blue'), ('pink-skin', 'Pink'), ('indigo-skin', 'Indigo'), ('light-blue-skin', 'Light Blue'), ('grey-skin', 'Grey')], max_length=32, null=True),
        ),
    ]
