# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20170612_1258'),
        ('main', '0018_club_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='vice_secretary',
        ),
        migrations.AddField(
            model_name='society',
            name='joint_secretary',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='joint_secy', to='oauth.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='ctype',
            field=models.CharField(choices=[('C', 'Club'), ('T', 'Team')], default='C', help_text='Specify type as Club or Team.', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='club',
            name='vice_captain_one',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_cap_one', to='oauth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='club',
            name='vice_captain_two',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_cap_two', to='oauth.UserProfile'),
        ),
    ]
