# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 14:32
from __future__ import unicode_literals

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0013_auto_20170702_2002'),
        ('main', '0022_sociallink_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('avatar', versatileimagefield.fields.VersatileImageField(upload_to='avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('photo', versatileimagefield.fields.VersatileImageField(upload_to='festival')),
                ('about', models.TextField(max_length=2048)),
                ('link', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Senate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('cover', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Upload high quality picture', null=True, upload_to='society_%Y', verbose_name='Cover')),
                ('skin', models.CharField(blank=True, choices=[('white-skin', 'White'), ('black-skin', 'Black'), ('cyan-skin', 'Cyan'), ('mdb-skin', 'MDB'), ('deep-purple-skin', 'Deep Purple'), ('navy-blue-skin', 'Navy Blue'), ('pink-skin', 'Pink'), ('indigo-skin', 'Indigo'), ('light-blue-skin', 'Light Blue'), ('grey-skin', 'Grey')], default='mdb-skin', help_text='Choose a skin while displaying senate page.', max_length=32)),
                ('custom_html', models.TextField(blank=True, default=None, help_text='Add custom HTML to view on society page.', null=True)),
                ('slug', models.SlugField(help_text='This will be used as URL. /senate/slug', unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('year', models.CharField(choices=[('2008', 2008), ('2009', 2009), ('2010', 2010), ('2011', 2011), ('2012', 2012), ('2013', 2013), ('2014', 2014), ('2015', 2015), ('2016', 2016), ('2017', 2017), ('2018', 2018)], max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Not a valid year!')])),
                ('coordinator_student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.FacultyAdvisor')),
            ],
        ),
        migrations.CreateModel(
            name='SenateMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('senate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Senate')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='core_members',
            field=models.ManyToManyField(to='oauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='club',
            name='resources_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='custom_html',
            field=models.TextField(blank=True, default=None, help_text='Add custom HTML to view on society page.', null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='custom_html',
            field=models.TextField(blank=True, default=None, help_text='Add custom HTML to view on club page.', null=True),
        ),
        migrations.AddField(
            model_name='senate',
            name='members',
            field=models.ManyToManyField(through='main.SenateMembership', to='oauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='society',
            name='faculty_advisor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.FacultyAdvisor'),
        ),
    ]
