# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 11:20
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20170625_1315'),
        ('main', '0025_auto_20170703_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Club')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery')),
            ],
        ),
    ]
