# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 10:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20170704_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='Not a valid number!')])),
                ('subject', models.CharField(max_length=128)),
                ('message', models.TextField(max_length=2048)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['social_media']},
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='fa_icon',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='icon_class',
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='social_media',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('LI', 'LinkedIn'), ('GP', 'Google Plus'), ('IG', 'Instagram'), ('GH', 'GitHub'), ('YT', 'YouTube')], max_length=2),
        ),
    ]
