# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20170706_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='gallery',
        ),
    ]
