# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralEvent',
        ),
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Club'),
        ),
    ]
