# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:16
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20170628_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
