# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_auto_20170630_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(max_length=160, verbose_name='about you'),
        ),
    ]
