# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0010_auto_20170702_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='userprofile',
            new_name='user',
        ),
    ]
