# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0011_auto_20170702_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['social_media']},
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='social_media',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('GP', 'Google Plus'), ('IG', 'Instagram'), ('GH', 'GitHub'), ('YT', 'YouTube')], max_length=2),
        ),
    ]
