# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0019_auto_20170710_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='about you'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='avatar/missing.png', upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Enter your skills, separated by comma.', max_length=1024, null=True),
        ),
    ]
