# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0023_userprofile_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hometown',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
