# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_auto_20170629_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='enroll_year',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prog',
            field=models.CharField(choices=[('BT', 'B.Tech'), ('MT', 'M.Tech'), ('PhD', 'PhD')], default='BT', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[('0', 'Alumni'), ('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], default='1', max_length=1),
        ),
    ]
