# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_auto_20170629_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(max_length=512, verbose_name='about you'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='/static/assets/others/missing.png', null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prog',
            field=models.CharField(choices=[('BT', 'B.Tech'), ('MT', 'M.Tech'), ('PhD', 'PhD')], default='BT', max_length=5, verbose_name='programme'),
        ),
    ]
