# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_auto_20170702_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('GP', 'Google Plus'), ('IG', 'Instagram'), ('GH', 'GitHub'), ('YT', 'YouTube'), ('EM', 'Email')], max_length=2)),
                ('link', models.URLField()),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.UserProfile')),
            ],
        ),
    ]
