# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 05:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0009_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
