# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0013_auto_20170702_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], default='1', max_length=1),
        ),
    ]
