# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 08:53
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0014_auto_20170703_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(default='static/assets/others/missing.png', upload_to='avatar'),
        ),
    ]
