# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_topic_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='topic',
        ),
        migrations.AddField(
            model_name='answer',
            name='topic',
            field=models.ManyToManyField(to='forum.Topic'),
        ),
    ]
