# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20170610_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='answers',
        ),
    ]
