# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_remove_topic_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='owner',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='owner',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='owner',
            new_name='author',
        ),
    ]
