# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20170716_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
