# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0024_auto_20170726_0000'),
        ('forum', '0024_auto_20170717_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='upvotes',
            field=models.ManyToManyField(related_name='topic_upvotes', to='oauth.UserProfile'),
        ),
    ]
