# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_topic_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='topic_upvotes', to='oauth.UserProfile'),
        ),
    ]
