# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0024_auto_20170726_0000'),
        ('forum', '0026_auto_20170801_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topicfavourite',
            name='author',
        ),
        migrations.RemoveField(
            model_name='topicfavourite',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='author',
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='answer_upvotes', to='oauth.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TopicFavourite',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
