# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 19:54
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='cover',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='club_%Y'),
        ),
        migrations.AlterField(
            model_name='society',
            name='cover',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='society_%Y'),
        ),
    ]
