# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20170625_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='ctype',
            field=models.CharField(choices=[('C', 'Club'), ('T', 'Team')], default='C', help_text='Specify type as Club or Team.', max_length=1),
        ),
    ]
