# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170625_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='skin',
            field=models.CharField(blank=True, choices=[('white-skin', 'White'), ('black-skin', 'Black'), ('cyan-skin', 'Cyan'), ('mdb-skin', 'MDB'), ('deep-purple-skin', 'Deep Purple'), ('navy-blue-skin', 'Navy Blue'), ('pink-skin', 'Pink'), ('indigo-skin', 'Indigo'), ('light-blue-skin', 'Light Blue'), ('grey-skin', 'Grey')], default='mdb-skin', help_text='Choose a skin while displaying society page.', max_length=32),
        ),
        migrations.AlterField(
            model_name='club',
            name='skin',
            field=models.CharField(blank=True, choices=[('white-skin', 'White'), ('black-skin', 'Black'), ('cyan-skin', 'Cyan'), ('mdb-skin', 'MDB'), ('deep-purple-skin', 'Deep Purple'), ('navy-blue-skin', 'Navy Blue'), ('pink-skin', 'Pink'), ('indigo-skin', 'Indigo'), ('light-blue-skin', 'Light Blue'), ('grey-skin', 'Grey')], default='mdb-skin', help_text='Choose a skin while displaying club page.', max_length=32),
        ),
    ]
