# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20170702_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senate',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='festival',
            name='name',
            field=models.CharField(choices=[('IGNS', 'Ignus'), ('VRCHS', 'Varchas'), ('SPNDN', 'Spandan'), ('NMBL', 'Nimble')], max_length=5),
        ),
        migrations.AlterField(
            model_name='senatemembership',
            name='role',
            field=models.CharField(choices=[('SECY', 'Student Secretary'), ('SER', 'Student Elected Representative')], max_length=5),
        ),
    ]
