# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='club',
            name='core_members',
            field=models.ManyToManyField(blank=True, null=True, to='oauth.UserProfile'),
        ),
    ]
