# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20170704_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='core_members',
            field=models.ManyToManyField(blank=True, to='oauth.UserProfile'),
        ),
    ]
