# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20170704_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-timestamp']},
        ),
    ]
