# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20170625_1315'),
        ('main', '0033_remove_activity_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='gallery',
            field=models.ForeignKey(blank=True, help_text='Select a gallery to link to this activity.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Gallery'),
        ),
    ]
