# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_activity_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='gallery',
        ),
    ]
