# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_activity_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='mentor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smentor', to='oauth.UserProfile'),
        ),
    ]
